on: push

jobs:

  code-format-c-cpp:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - name: Install required packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates git clang-format
          apt-get clean
          rm -rf /var/lib/apt/lists/*
          clang-format --version
      - uses: actions/checkout@v2
      - name: Run clang-format
        run: |
          git ls-files '*.cpp' '*.h' '*.hpp' | xargs clang-format --verbose -i
          git diff --exit-code

  code-format-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install autopep8
        run: |
          pip3 install autopep8
          autopep8 --version
      - name: Run autopep8
        run: git ls-files '*.py' | xargs autopep8 --diff --exit-code

  run-tests:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y --no-install-recommends build-essential clang pkg-config cmake libblas-dev libopenblas-dev libatlas-base-dev libfftw3-dev
          apt-get clean
          rm -rf /var/lib/apt/lists/*
      - name: Build tests
        run: |
          mkdir build/
          cd build/
          cmake .. -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTING=TRUE -DNO_QMKL6=TRUE
          make
      - name: Run tests
        run: |
          tail -n +1 /proc/cpuinfo /proc/meminfo
          echo
          cd build/
          ctest -V

  run-tests-mkl:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    defaults:
      run:
        shell: bash
    steps:
      - name: Install required packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates curl gnupg make cmake binutils libstdc++-9-dev
          curl --silent 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB' | apt-key add -
          echo 'deb https://apt.repos.intel.com/oneapi all main' >>/etc/apt/sources.list.d/intel.list
          apt-get update
          apt-get install -y --no-install-recommends intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mkl-devel
          apt-get clean
          rm -rf /var/lib/apt/lists/*
      - uses: actions/checkout@v2
      - name: Build tests
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B build/ -D CMAKE_CXX_COMPILER=icpx -D mkl_FOUND=TRUE -D BUILD_TESTING=TRUE -D NO_QMKL6=TRUE
          cmake --build build/ -v
      - name: Run tests
        run: |
          tail -n +1 /proc/cpuinfo /proc/meminfo
          echo
          source /opt/intel/oneapi/setvars.sh
          cd build/
          ctest -V
